/**
 * Generate a simple SEO/AI-friendly static HTML snapshot page.
 * Input: profile + tweets array from parser.
 */

function generateJSONLD(profile, tweets) {
  return {
    "@context": "https://schema.org",
    "@type": "Person",
    "name": profile.name || profile.screen_name,
    "alternateName": "@" + (profile.screen_name || ""),
    "description": profile.description || profile.bio || "",
    "url": "https://xsnapshot.example/@" + (profile.screen_name || ""),
    "sameAs": "https://x.com/" + (profile.screen_name || ""),
    "mainEntityOfPage": {
      "@type": "ItemList",
      "name": "Tweet Snapshot",
      "numberOfItems": tweets.length,
      "itemListElement": tweets.slice(0, 50).map((t, i) => ({
        "@type": "ListItem",
        "position": i + 1,
        "item": {
          "@type": "SocialMediaPosting",
          "identifier": t.id,
          "datePublished": t.created_at,
          "text": t.text,
          "author": { "@type": "Person", "name": profile.name }
        }
      }))
    }
  };
}

function generateHTML(profile, tweets, snapshotDate) {
  const handle = profile.screen_name || "unknown";
  const jsonld = JSON.stringify(generateJSONLD(profile, tweets));
  const tweetCards = tweets.slice(0, 200).map(t => `
    <article class="tweet" id="t-${t.id}">
      <time datetime="${t.created_at}">${t.created_at}</time>
      <p>${escapeHtml(t.text)}</p>
      ${t.media && t.media.length ? `<div class="media">Media: ${t.media.map(m => m.media_url_https || m.url).join(', ')}</div>` : ''}
    </article>`).join('\n');

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>@${handle} — XSnapshot (as of ${snapshotDate})</title>
  <meta name="description" content="Permanent public snapshot of @${handle} tweets from official X archive. Full history, searchable, crawlable.">
  <meta name="robots" content="index, follow">
  <link rel="canonical" href="https://xsnapshot.example/@${handle}">
  <script type="application/ld+json">${jsonld}</script>
  <style>
    body { font-family: system-ui, sans-serif; max-width: 680px; margin: 0 auto; padding: 1rem; line-height: 1.5; }
    .banner { background: #f0f0f0; padding: 0.75rem; border-radius: 8px; margin-bottom: 1.5rem; font-size: 0.9rem; }
    .tweet { border-bottom: 1px solid #eee; padding: 1rem 0; }
    time { color: #666; font-size: 0.85rem; }
  </style>
</head>
<body>
  <header>
    <h1>@${handle}</h1>
    <p>${escapeHtml(profile.description || profile.bio || '')}</p>
    <div class="banner">
      <strong>Official X archive snapshot taken ${snapshotDate}.</strong><br>
      Not a live feed. Media links may break. This page is user-submitted and claimable.
      Google and AI crawlers may index it permanently.
    </div>
  </header>
  <main>
    <p>${tweets.length} public tweets in this snapshot.</p>
    ${tweetCards}
  </main>
  <footer>
    <p>Generated by <a href="https://github.com/VeigaPunk/xsnapshot">XSnapshot</a>. Data remains the user's. Export / delete available after claim.</p>
  </footer>
</body>
</html>`;
}

function escapeHtml(str) {
  return String(str)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

module.exports = { generateHTML, generateJSONLD };
